name: computer-vision
channels:
- anaconda
- conda-forge
- pytorch
dependencies:
- python=3.7
- jupyter
- ipython
- pytorch==1.6.0
- torchvision==0.7.0
- pip:
  - opencv-python==4.0.1.24
  - scikit-learn==0.23.1
  - matplotlib==3.2.2
  - numpy==1.18.5
